channels:
  - defaults
dependencies:
  - python=3.9
  - pip=22.1.*
  - pandas=1.4.*
  - spacy=3.3.*
  - nltk=3.7
  - pip:
    - sastrawi==1.0.1
    - jupyterlab==3.4.7
    - jupyterlab-vim==0.15.1
    - tabulate==0.8.10
